# Generated by Django 4.2 on 2023-04-29 18:38

import apiApplication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicProjects",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("desciption", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="AssociativeLife",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("desciption", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Certficates",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("desciption", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("desciption", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Languages",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PersonalProfile",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("intro", models.CharField(max_length=200)),
                (
                    "phone",
                    models.IntegerField(
                        validators=[apiApplication.models.validate_phone_number]
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                ("birthdate", models.DateField()),
                ("linkedin", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="ProfessionalExperience",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("header", models.CharField(max_length=50)),
                ("desciption", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Skills",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("desciption", models.CharField(max_length=200)),
            ],
        ),
    ]
